# Generated by Django 6.0.3 on 2026-03-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_alter_userprofile_bench_1rm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bench_1rm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deadlift_1rm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='squat_1rm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
